title: Planet A Project
author: doctoralehs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my description. Here it is. You see it now. I like turtles. Just kidding lol.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
